Vision:
  fast:
    nonmaxSuppression: 1
    type: 2
    threshold: 10
  #sift:
  #orb:
Camera:
  fx: 912.8844558325202
  fy: 916.1788304640794
  cx: 488.3668390339133
  cy: 377.42470274611975
  cy_aligned: 175
  pitch: -13
  stream: null
YOLO:
  path: yolo_dataset/mixed.pt
  #path: yolo_dataset/indoor.pt
Control:
  pid:
    screen_yaw:
      #kp: -0.002
      #ki: -0.0001
      #kd: -0.0005
      kp: -0.002
      ki: -0.00025
      kd: -0.0005
      min: -0.2
      max: 0.2
    screen_throttle:
      kp: 0.004
      ki: 0.001
      kd: 0.00125
      min: -0.3
      max: 0.3
    throttle:
      #initial
      #kp: 0.03333333333333333
      #ki: 0.025
      #kd: 0.016666666666666666
      #some overshot
      #kp: 0.0165
      #ki: 0.0132
      #kd: 0.0136125
      #newest
      #kp: 0.03
      #ki: 0.00003
      #kd: 0.045
      
      #my PD
      kp: 0.02
      ki: 0.000001 #optional
      kd: 0.045
      min: -0.3
      max: 0.3
    pitch:
      kp: 0.006666666666666667
      ki: 0.0008333333333333334
      kd: 0.006666666666666667
      min: -0.2
      max: 0.2
    roll:
      #kp: 0.006666666666666667
      #ki: 0.0013333333333333333
      #kd: 0.013333333333333334
      #very slow
      #kp: 0.0067
      #ki: 0.0000067
      #kd: 0.01005
      #new
      kp: 0.008
      ki: 0.000001
      kd: 0.045
      min: -0.5
      max: 0.5
    yaw:
      kp: 0.1
      ki: 0.1
      kd: 0.01
      min: -0.5
      max: 0.5
  folder_odom: exp3/17.txt
  ty: 10
  drone_hook_center: -8 #-8 for the printed hook, -5 for steel hook
  desired_fps: 25
WiFi:
  #interface: wlp61s0

  #interface: wlx0c9d92b767ea
  #ssid: TELLO-98FC9A
  #ip: 192.168.10.20

  interface: wlxd8ec5e0a30b5
  ssid: TELLO-98FD38
  ip: 192.168.10.30

  password: TELLOBISG
RechargeStation:
  #ip: "192.168.1.11"
  ip: ""
  port: 2810
